[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15, fail_on_revert = false, call_override = false }
fs_permissions = [{ access = "read", path = "./" }]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 15 }

[profile.lite]
fuzz = { runs = 10 }
invariant = { runs = 10, depth = 5 }

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/6ChCkEoo-jvGgoa85eb9G"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/YOUR_MAINNET_KEY"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[doc]
out = "docs"